# Generated by Django 4.2.4 on 2023-09-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_ordinaryuser_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinaryuser',
            name='email',
            field=models.CharField(blank=True, default='', max_length=125),
        ),
    ]
